# Generated by Django 3.2.17 on 2023-03-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0002_auto_20230308_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_work_request',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cunstruction.user'),
        ),
    ]
