# Generated by Django 3.2.17 on 2023-03-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0003_alter_usr_work_request_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='wid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cunstruction.worker'),
        ),
    ]
