# Generated by Django 3.2.17 on 2023-03-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0004_job_wid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='wid',
        ),
        migrations.CreateModel(
            name='assignJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobStatus', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cunstruction.contractor')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cunstruction.job')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cunstruction.worker')),
            ],
        ),
    ]
