# Generated by Django 3.2.17 on 2023-03-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0005_auto_20230309_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobStatus',
        ),
        migrations.AddField(
            model_name='job',
            name='jobDetails',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(max_length=90),
        ),
    ]
