# Generated by Django 3.2.17 on 2023-03-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0006_auto_20230309_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr_work_request',
            name='jid',
        ),
        migrations.AddField(
            model_name='usr_work_request',
            name='work',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
