# Generated by Django 3.2.17 on 2023-03-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0009_alter_contractorworks_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorworks',
            name='status',
            field=models.CharField(default=2, max_length=90),
            preserve_default=False,
        ),
    ]
