# Generated by Django 3.2.17 on 2023-03-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0010_contractorworks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorworks',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usr_work_request',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='usr_work_request',
            name='work',
        ),
        migrations.AddField(
            model_name='usr_work_request',
            name='cwid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cunstruction.contractorworks'),
            preserve_default=False,
        ),
    ]
