# Generated by Django 3.2.17 on 2023-05-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunstruction', '0012_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='probationPeriod',
            field=models.CharField(default=2, max_length=90),
            preserve_default=False,
        ),
    ]
